In [17]:
from typing import List
import tensorflow as tf
import numpy as np
from tensorflow.keras import datasets, layers, models

import weight_manager
# https://www.geeksforgeeks.org/ordereddict-in-python/

In [23]:
# simple model creation

model = tf.keras.Sequential()
model.add(layers.Dense(units=10, input_shape=(1,)))
model.add(layers.Dense(units=10))
# model.add(layers.Conv2D(32, (3, 3), activation='relu', input_shape=(32,32,3)))
# model.add(layers.MaxPooling2D((2, 2)))
# model.add(layers.Conv2D(64, (3, 3), activation='relu'))
# model.add(layers.MaxPooling2D((2, 2)))
# model.add(layers.Conv2D(64, (3, 3), activation='relu'))

optimizer = tf.keras.optimizers.Adam(learning_rate=0.001)


In [19]:
# automatic name creation
model.layers[0].name,model.layers[1].name

('dense_2', 'dense_3')

In [20]:
model.layers[0].get_weights() # gives (weights, bias)

[array([[ 0.5156755 , -0.11075705,  0.37524265,  0.20820606,  0.50997335,
         -0.45109797, -0.04316729, -0.6919177 , -0.08060271, -0.30794325]],
       dtype=float32),
 array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32)]

In [21]:
f'{2+2}'

'4'

In [22]:
weight_manager.state_dict(model)

OrderedDict([('dense_2.weight',
              <tf.Variable 'Variable:0' shape=(1, 10) dtype=float64, numpy=
              array([[ 0.51567549, -0.11075705,  0.37524265,  0.20820606,  0.50997335,
                      -0.45109797, -0.04316729, -0.69191772, -0.08060271, -0.30794325]])>),
             ('dense_2.bias',
              <tf.Variable 'Variable:0' shape=(10,) dtype=float64, numpy=array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])>),
             ('dense_3.weight',
              <tf.Variable 'Variable:0' shape=(10, 10) dtype=float64, numpy=
              array([[-0.1189574 ,  0.11489117, -0.43617234,  0.54548943, -0.49006334,
                       0.19727254,  0.52312803, -0.1740284 , -0.12193546, -0.04205656],
                     [-0.10620451,  0.52559257, -0.40713769,  0.02552879, -0.54418039,
                      -0.0454402 ,  0.38965338,  0.3931843 , -0.00222808,  0.44847679],
                     [ 0.18520063, -0.47330979,  0.50398564,  0.36348563, -0.3389042 ,
             

In [24]:
optimizer.get_config() # OK, et 'state ?'

{'name': 'Adam',
 'weight_decay': None,
 'clipnorm': None,
 'global_clipnorm': None,
 'clipvalue': None,
 'use_ema': False,
 'ema_momentum': 0.99,
 'ema_overwrite_frequency': None,
 'jit_compile': False,
 'is_legacy_optimizer': False,
 'learning_rate': 0.001,
 'beta_1': 0.9,
 'beta_2': 0.999,
 'epsilon': 1e-07,
 'amsgrad': False}