# Importing libraries

In [1]:
from typing import List
import tensorflow as tf
import numpy as np
from tensorflow.keras import datasets, layers, models

import weight_manager

import cloudpickle

import pathlib
# https://www.geeksforgeeks.org/ordereddict-in-python/

# Creating model 

In [2]:
# simple model creation

model = tf.keras.Sequential()
model.add(layers.Dense(units=10, input_shape=(1,)))
model.add(layers.Dense(units=10))
# model.add(layers.Conv2D(32, (3, 3), activation='relu', input_shape=(32,32,3)))
# model.add(layers.MaxPooling2D((2, 2)))
# model.add(layers.Conv2D(64, (3, 3), activation='relu'))
# model.add(layers.MaxPooling2D((2, 2)))
# model.add(layers.Conv2D(64, (3, 3), activation='relu'))

optimizer = tf.keras.optimizers.Adam(learning_rate=0.001)
loss= tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)


## Testing layers methods

In [3]:
# automatic name creation
model.layers[0].name,model.layers[1].name

('dense', 'dense_1')

In [4]:
model.layers[0].get_weights() # gives (weights, bias)

[array([[ 0.568031  , -0.48442164,  0.2718088 , -0.11627907, -0.6603033 ,
          0.06481224, -0.09219819, -0.46340498, -0.09349555, -0.25750738]],
       dtype=float32),
 array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32)]

In [5]:
f'{2+2}'

'4'

In [6]:
weight_manager.model_state_dict(model)

OrderedDict([('config',
              {'name': 'sequential',
               'layers': [{'class_name': 'InputLayer',
                 'config': {'batch_input_shape': (None, 1),
                  'dtype': 'float32',
                  'sparse': False,
                  'ragged': False,
                  'name': 'dense_input'}},
                {'class_name': 'Dense',
                 'config': {'name': 'dense',
                  'trainable': True,
                  'dtype': 'float32',
                  'batch_input_shape': (None, 1),
                  'units': 10,
                  'activation': 'linear',
                  'use_bias': True,
                  'kernel_initializer': {'class_name': 'GlorotUniform',
                   'config': {'seed': None}},
                  'bias_initializer': {'class_name': 'Zeros', 'config': {}},
                  'kernel_regularizer': None,
                  'bias_regularizer': None,
                  'activity_regularizer': None,
                  'ke

In [7]:
optimizer.get_config() # OK, et 'state ?'

{'name': 'Adam',
 'weight_decay': None,
 'clipnorm': None,
 'global_clipnorm': None,
 'clipvalue': None,
 'use_ema': False,
 'ema_momentum': 0.99,
 'ema_overwrite_frequency': None,
 'jit_compile': False,
 'is_legacy_optimizer': False,
 'learning_rate': 0.001,
 'beta_1': 0.9,
 'beta_2': 0.999,
 'epsilon': 1e-07,
 'amsgrad': False}

In [8]:
model.get_config()

{'name': 'sequential',
 'layers': [{'class_name': 'InputLayer',
   'config': {'batch_input_shape': (None, 1),
    'dtype': 'float32',
    'sparse': False,
    'ragged': False,
    'name': 'dense_input'}},
  {'class_name': 'Dense',
   'config': {'name': 'dense',
    'trainable': True,
    'dtype': 'float32',
    'batch_input_shape': (None, 1),
    'units': 10,
    'activation': 'linear',
    'use_bias': True,
    'kernel_initializer': {'class_name': 'GlorotUniform',
     'config': {'seed': None}},
    'bias_initializer': {'class_name': 'Zeros', 'config': {}},
    'kernel_regularizer': None,
    'bias_regularizer': None,
    'activity_regularizer': None,
    'kernel_constraint': None,
    'bias_constraint': None}},
  {'class_name': 'Dense',
   'config': {'name': 'dense_1',
    'trainable': True,
    'dtype': 'float32',
    'units': 10,
    'activation': 'linear',
    'use_bias': True,
    'kernel_initializer': {'class_name': 'GlorotUniform',
     'config': {'seed': None}},
    'bias_init

In [9]:
model.get_weights() #list

[array([[ 0.568031  , -0.48442164,  0.2718088 , -0.11627907, -0.6603033 ,
          0.06481224, -0.09219819, -0.46340498, -0.09349555, -0.25750738]],
       dtype=float32),
 array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32),
 array([[-2.5710434e-01, -5.2817756e-01, -4.8678207e-01,  1.4984560e-01,
         -1.1217326e-01,  3.3078176e-01,  2.1074480e-01, -5.3007019e-01,
         -3.8125664e-01, -2.6968446e-01],
        [-4.2986512e-01, -5.4725575e-01,  8.0295205e-03, -1.8907857e-01,
         -2.0286754e-01,  2.0328492e-01,  2.5763780e-01,  1.9300717e-01,
          4.1100842e-01, -2.1937782e-01],
        [-3.5328734e-01, -3.2448280e-01,  3.9162552e-01, -1.4200982e-01,
         -2.8680119e-01,  4.8261404e-02,  5.3295887e-01,  4.6619356e-02,
         -4.3212533e-01,  4.8965883e-01],
        [ 4.6346104e-01,  3.1944096e-02,  2.5486267e-01, -6.7811221e-02,
         -2.9579329e-01,  1.7404604e-01,  2.7579010e-02,  4.5778394e-01,
         -5.4558027e-01,  1.6901869e-01],
        [-

# Testing serialization of tf objects

In [10]:
checkpoint = {
    "model_state_dict" : weight_manager.model_state_dict(model),
    "optimizer_state_dict" : optimizer.get_config()
}

In [11]:
with open(pathlib.Path.cwd() / "test_serialization", "wb") as f:
    cloudpickle.dump(checkpoint, f)

In [12]:
with open(pathlib.Path.cwd() / "test_serialization", "rb") as f:
        checkpoint = cloudpickle.load(f)

In [13]:
checkpoint

{'model_state_dict': OrderedDict([('config',
               {'name': 'sequential',
                'layers': [{'class_name': 'InputLayer',
                  'config': {'batch_input_shape': (None, 1),
                   'dtype': 'float32',
                   'sparse': False,
                   'ragged': False,
                   'name': 'dense_input'}},
                 {'class_name': 'Dense',
                  'config': {'name': 'dense',
                   'trainable': True,
                   'dtype': 'float32',
                   'batch_input_shape': (None, 1),
                   'units': 10,
                   'activation': 'linear',
                   'use_bias': True,
                   'kernel_initializer': {'class_name': 'GlorotUniform',
                    'config': {'seed': None}},
                   'bias_initializer': {'class_name': 'Zeros', 'config': {}},
                   'kernel_regularizer': None,
                   'bias_regularizer': None,
                   'activity

In [14]:
optimizer_s = tf.keras.optimizers.serialize(optimizer)

In [15]:
type(optimizer.get_config()), type(optimizer_s)

(dict, dict)

In [16]:
optimizer.get_config(), optimizer_s

({'name': 'Adam',
  'weight_decay': None,
  'clipnorm': None,
  'global_clipnorm': None,
  'clipvalue': None,
  'use_ema': False,
  'ema_momentum': 0.99,
  'ema_overwrite_frequency': None,
  'jit_compile': False,
  'is_legacy_optimizer': False,
  'learning_rate': 0.001,
  'beta_1': 0.9,
  'beta_2': 0.999,
  'epsilon': 1e-07,
  'amsgrad': False},
 {'class_name': 'Custom>Adam',
  'config': {'name': 'Adam',
   'weight_decay': None,
   'clipnorm': None,
   'global_clipnorm': None,
   'clipvalue': None,
   'use_ema': False,
   'ema_momentum': 0.99,
   'ema_overwrite_frequency': None,
   'jit_compile': False,
   'is_legacy_optimizer': False,
   'learning_rate': 0.001,
   'beta_1': 0.9,
   'beta_2': 0.999,
   'epsilon': 1e-07,
   'amsgrad': False}})

In [17]:
tf.keras.optimizers.serialize

<function keras.optimizers.serialize(optimizer, use_legacy_format=False)>

In [18]:
model_s_d= tf.keras.layers.serialize(model)

In [19]:
model_s_d

{'class_name': 'Sequential',
 'config': {'name': 'sequential',
  'layers': [{'class_name': 'InputLayer',
    'config': {'batch_input_shape': (None, 1),
     'dtype': 'float32',
     'sparse': False,
     'ragged': False,
     'name': 'dense_input'}},
   {'class_name': 'Dense',
    'config': {'name': 'dense',
     'trainable': True,
     'dtype': 'float32',
     'batch_input_shape': (None, 1),
     'units': 10,
     'activation': 'linear',
     'use_bias': True,
     'kernel_initializer': {'class_name': 'GlorotUniform',
      'config': {'seed': None}},
     'bias_initializer': {'class_name': 'Zeros', 'config': {}},
     'kernel_regularizer': None,
     'bias_regularizer': None,
     'activity_regularizer': None,
     'kernel_constraint': None,
     'bias_constraint': None}},
   {'class_name': 'Dense',
    'config': {'name': 'dense_1',
     'trainable': True,
     'dtype': 'float32',
     'units': 10,
     'activation': 'linear',
     'use_bias': True,
     'kernel_initializer': {'class_

In [20]:
model.get_config()

{'name': 'sequential',
 'layers': [{'class_name': 'InputLayer',
   'config': {'batch_input_shape': (None, 1),
    'dtype': 'float32',
    'sparse': False,
    'ragged': False,
    'name': 'dense_input'}},
  {'class_name': 'Dense',
   'config': {'name': 'dense',
    'trainable': True,
    'dtype': 'float32',
    'batch_input_shape': (None, 1),
    'units': 10,
    'activation': 'linear',
    'use_bias': True,
    'kernel_initializer': {'class_name': 'GlorotUniform',
     'config': {'seed': None}},
    'bias_initializer': {'class_name': 'Zeros', 'config': {}},
    'kernel_regularizer': None,
    'bias_regularizer': None,
    'activity_regularizer': None,
    'kernel_constraint': None,
    'bias_constraint': None}},
  {'class_name': 'Dense',
   'config': {'name': 'dense_1',
    'trainable': True,
    'dtype': 'float32',
    'units': 10,
    'activation': 'linear',
    'use_bias': True,
    'kernel_initializer': {'class_name': 'GlorotUniform',
     'config': {'seed': None}},
    'bias_init

# Finding how to properly initialize models with config, weights, optimizer, loss, metrics

For a model:
- *config* = its structure (layers' type and dimension)
- *weights* = layers' weights
- *compile config* = its optimizer, loss, metrics and other

We want here to understand how to transfer those caracteristics between model, and how to save and load them.

To get the config with which the model has been ***created***

In [21]:
model.get_config()

{'name': 'sequential',
 'layers': [{'class_name': 'InputLayer',
   'config': {'batch_input_shape': (None, 1),
    'dtype': 'float32',
    'sparse': False,
    'ragged': False,
    'name': 'dense_input'}},
  {'class_name': 'Dense',
   'config': {'name': 'dense',
    'trainable': True,
    'dtype': 'float32',
    'batch_input_shape': (None, 1),
    'units': 10,
    'activation': 'linear',
    'use_bias': True,
    'kernel_initializer': {'class_name': 'GlorotUniform',
     'config': {'seed': None}},
    'bias_initializer': {'class_name': 'Zeros', 'config': {}},
    'kernel_regularizer': None,
    'bias_regularizer': None,
    'activity_regularizer': None,
    'kernel_constraint': None,
    'bias_constraint': None}},
  {'class_name': 'Dense',
   'config': {'name': 'dense_1',
    'trainable': True,
    'dtype': 'float32',
    'units': 10,
    'activation': 'linear',
    'use_bias': True,
    'kernel_initializer': {'class_name': 'GlorotUniform',
     'config': {'seed': None}},
    'bias_init

In [22]:
model.get_weights()

[array([[ 0.568031  , -0.48442164,  0.2718088 , -0.11627907, -0.6603033 ,
          0.06481224, -0.09219819, -0.46340498, -0.09349555, -0.25750738]],
       dtype=float32),
 array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32),
 array([[-2.5710434e-01, -5.2817756e-01, -4.8678207e-01,  1.4984560e-01,
         -1.1217326e-01,  3.3078176e-01,  2.1074480e-01, -5.3007019e-01,
         -3.8125664e-01, -2.6968446e-01],
        [-4.2986512e-01, -5.4725575e-01,  8.0295205e-03, -1.8907857e-01,
         -2.0286754e-01,  2.0328492e-01,  2.5763780e-01,  1.9300717e-01,
          4.1100842e-01, -2.1937782e-01],
        [-3.5328734e-01, -3.2448280e-01,  3.9162552e-01, -1.4200982e-01,
         -2.8680119e-01,  4.8261404e-02,  5.3295887e-01,  4.6619356e-02,
         -4.3212533e-01,  4.8965883e-01],
        [ 4.6346104e-01,  3.1944096e-02,  2.5486267e-01, -6.7811221e-02,
         -2.9579329e-01,  1.7404604e-01,  2.7579010e-02,  4.5778394e-01,
         -5.4558027e-01,  1.6901869e-01],
        [-

To get the config with which the model has been ***compiled*** : 

In [23]:
type(model.get_compile_config())

NoneType

it has not been compiled yet so it is normal
if we compile it :

In [24]:
model.compile(optimizer=optimizer, loss=loss)

In [25]:
conf= model.get_compile_config()

In [26]:
conf

{'optimizer': {'module': 'keras.optimizers',
  'class_name': 'Adam',
  'config': {'name': 'Adam',
   'weight_decay': None,
   'clipnorm': None,
   'global_clipnorm': None,
   'clipvalue': None,
   'use_ema': False,
   'ema_momentum': 0.99,
   'ema_overwrite_frequency': None,
   'jit_compile': False,
   'is_legacy_optimizer': False,
   'learning_rate': 0.0010000000474974513,
   'beta_1': 0.9,
   'beta_2': 0.999,
   'epsilon': 1e-07,
   'amsgrad': False},
  'registered_name': None},
 'loss': {'module': 'keras.losses',
  'class_name': 'SparseCategoricalCrossentropy',
  'config': {'reduction': 'auto',
   'name': 'sparse_categorical_crossentropy',
   'from_logits': True,
   'ignore_class': None},
  'registered_name': None},
 'metrics': None,
 'loss_weights': None,
 'weighted_metrics': None,
 'run_eagerly': None,
 'steps_per_execution': None,
 'jit_compile': None}

In [27]:
conf.keys()

dict_keys(['optimizer', 'loss', 'metrics', 'loss_weights', 'weighted_metrics', 'run_eagerly', 'steps_per_execution', 'jit_compile'])

In [28]:
conf['loss_weights']

Creating a new model

In [29]:
model2 = tf.keras.Sequential()

Compiling it from model's config, we see the differences between configs

In [30]:
model2.compile_from_config(conf)

In [31]:
model2.get_config()

{'name': 'sequential_1', 'layers': []}

In [32]:
model2.get_compile_config()

{'optimizer': {'module': 'keras.optimizers',
  'class_name': 'Adam',
  'config': {'name': 'Adam',
   'weight_decay': None,
   'clipnorm': None,
   'global_clipnorm': None,
   'clipvalue': None,
   'use_ema': False,
   'ema_momentum': 0.99,
   'ema_overwrite_frequency': None,
   'jit_compile': False,
   'is_legacy_optimizer': False,
   'learning_rate': 0.0010000000474974513,
   'beta_1': 0.9,
   'beta_2': 0.999,
   'epsilon': 1e-07,
   'amsgrad': False},
  'registered_name': None},
 'loss': {'module': 'keras.losses',
  'class_name': 'SparseCategoricalCrossentropy',
  'config': {'reduction': 'auto',
   'name': 'sparse_categorical_crossentropy',
   'from_logits': True,
   'ignore_class': None},
  'registered_name': None},
 'metrics': None,
 'loss_weights': None,
 'weighted_metrics': None,
 'run_eagerly': None,
 'steps_per_execution': None,
 'jit_compile': None}

In [33]:
model3=tf.keras.Sequential()

In [34]:
model3.from_config(model.get_config())

In [35]:
model3.get_config()

{'name': 'sequential_2', 'layers': []}

In [39]:
model3.compile_from_config(model.get_compile_config())

In [40]:
model3.get_compile_config()

{'optimizer': {'module': 'keras.optimizers',
  'class_name': 'Adam',
  'config': {'name': 'Adam',
   'weight_decay': None,
   'clipnorm': None,
   'global_clipnorm': None,
   'clipvalue': None,
   'use_ema': False,
   'ema_momentum': 0.99,
   'ema_overwrite_frequency': None,
   'jit_compile': False,
   'is_legacy_optimizer': False,
   'learning_rate': 0.0010000000474974513,
   'beta_1': 0.9,
   'beta_2': 0.999,
   'epsilon': 1e-07,
   'amsgrad': False},
  'registered_name': None},
 'loss': {'module': 'keras.losses',
  'class_name': 'SparseCategoricalCrossentropy',
  'config': {'reduction': 'auto',
   'name': 'sparse_categorical_crossentropy',
   'from_logits': True,
   'ignore_class': None},
  'registered_name': None},
 'metrics': None,
 'loss_weights': None,
 'weighted_metrics': None,
 'run_eagerly': None,
 'steps_per_execution': None,
 'jit_compile': None}

In [41]:
model3.get_config()

{'name': 'sequential_2', 'layers': []}

To instanciate a new model from the config of an existing one, we need to apply `.from_config` to the model class we want to create

In [42]:
model4= tf.keras.Sequential().from_config(model.get_config())

In [43]:
model4.get_config()

{'name': 'sequential',
 'layers': [{'class_name': 'InputLayer',
   'config': {'batch_input_shape': (None, 1),
    'dtype': 'float32',
    'sparse': False,
    'ragged': False,
    'name': 'dense_input'}},
  {'class_name': 'Dense',
   'config': {'name': 'dense',
    'trainable': True,
    'dtype': 'float32',
    'batch_input_shape': (None, 1),
    'units': 10,
    'activation': 'linear',
    'use_bias': True,
    'kernel_initializer': {'class_name': 'GlorotUniform',
     'config': {'seed': None}},
    'bias_initializer': {'class_name': 'Zeros', 'config': {}},
    'kernel_regularizer': None,
    'bias_regularizer': None,
    'activity_regularizer': None,
    'kernel_constraint': None,
    'bias_constraint': None}},
  {'class_name': 'Dense',
   'config': {'name': 'dense_1',
    'trainable': True,
    'dtype': 'float32',
    'units': 10,
    'activation': 'linear',
    'use_bias': True,
    'kernel_initializer': {'class_name': 'GlorotUniform',
     'config': {'seed': None}},
    'bias_init