# Importing libraries

In [13]:
from typing import List
import tensorflow as tf
import numpy as np
from tensorflow.keras import datasets, layers, models

import weight_manager

import cloudpickle

import pathlib
# https://www.geeksforgeeks.org/ordereddict-in-python/

# Creating model 

In [14]:
# simple model creation

model = tf.keras.Sequential()
model.add(layers.Dense(units=10, input_shape=(1,)))
model.add(layers.Dense(units=10))
# model.add(layers.Conv2D(32, (3, 3), activation='relu', input_shape=(32,32,3)))
# model.add(layers.MaxPooling2D((2, 2)))
# model.add(layers.Conv2D(64, (3, 3), activation='relu'))
# model.add(layers.MaxPooling2D((2, 2)))
# model.add(layers.Conv2D(64, (3, 3), activation='relu'))

optimizer = tf.keras.optimizers.Adam(learning_rate=0.001)


## Testing layers methods

In [15]:
# automatic name creation
model.layers[0].name,model.layers[1].name

('dense_2', 'dense_3')

In [16]:
model.layers[0].get_weights() # gives (weights, bias)

[array([[-0.3808652 , -0.6323739 , -0.6473553 , -0.71325994, -0.08594793,
         -0.22682303,  0.28857   , -0.18017793,  0.08728844, -0.14109099]],
       dtype=float32),
 array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32)]

In [17]:
f'{2+2}'

'4'

In [18]:
weight_manager.model_state_dict(model)

OrderedDict([('config',
              {'name': 'sequential_1',
               'layers': [{'class_name': 'InputLayer',
                 'config': {'batch_input_shape': (None, 1),
                  'dtype': 'float32',
                  'sparse': False,
                  'ragged': False,
                  'name': 'dense_2_input'}},
                {'class_name': 'Dense',
                 'config': {'name': 'dense_2',
                  'trainable': True,
                  'dtype': 'float32',
                  'batch_input_shape': (None, 1),
                  'units': 10,
                  'activation': 'linear',
                  'use_bias': True,
                  'kernel_initializer': {'class_name': 'GlorotUniform',
                   'config': {'seed': None}},
                  'bias_initializer': {'class_name': 'Zeros', 'config': {}},
                  'kernel_regularizer': None,
                  'bias_regularizer': None,
                  'activity_regularizer': None,
               

In [19]:
optimizer.get_config() # OK, et 'state ?'

{'name': 'Adam',
 'weight_decay': None,
 'clipnorm': None,
 'global_clipnorm': None,
 'clipvalue': None,
 'use_ema': False,
 'ema_momentum': 0.99,
 'ema_overwrite_frequency': None,
 'jit_compile': False,
 'is_legacy_optimizer': False,
 'learning_rate': 0.001,
 'beta_1': 0.9,
 'beta_2': 0.999,
 'epsilon': 1e-07,
 'amsgrad': False}

In [20]:
model.get_config()

{'name': 'sequential_1',
 'layers': [{'class_name': 'InputLayer',
   'config': {'batch_input_shape': (None, 1),
    'dtype': 'float32',
    'sparse': False,
    'ragged': False,
    'name': 'dense_2_input'}},
  {'class_name': 'Dense',
   'config': {'name': 'dense_2',
    'trainable': True,
    'dtype': 'float32',
    'batch_input_shape': (None, 1),
    'units': 10,
    'activation': 'linear',
    'use_bias': True,
    'kernel_initializer': {'class_name': 'GlorotUniform',
     'config': {'seed': None}},
    'bias_initializer': {'class_name': 'Zeros', 'config': {}},
    'kernel_regularizer': None,
    'bias_regularizer': None,
    'activity_regularizer': None,
    'kernel_constraint': None,
    'bias_constraint': None}},
  {'class_name': 'Dense',
   'config': {'name': 'dense_3',
    'trainable': True,
    'dtype': 'float32',
    'units': 10,
    'activation': 'linear',
    'use_bias': True,
    'kernel_initializer': {'class_name': 'GlorotUniform',
     'config': {'seed': None}},
    'bia

In [21]:
model.get_weights() #list

[array([[-0.3808652 , -0.6323739 , -0.6473553 , -0.71325994, -0.08594793,
         -0.22682303,  0.28857   , -0.18017793,  0.08728844, -0.14109099]],
       dtype=float32),
 array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32),
 array([[ 0.25114197, -0.3110532 , -0.5003104 , -0.4473185 ,  0.08007652,
         -0.48265213,  0.17360139,  0.18494129,  0.19642603, -0.45812982],
        [-0.05974379,  0.25578475,  0.16984504,  0.42956543, -0.12409678,
          0.35256088,  0.2756719 , -0.35149473,  0.1383034 ,  0.4237216 ],
        [-0.0387336 , -0.25194287,  0.2911505 ,  0.5191808 , -0.24995339,
         -0.03677022, -0.5375024 , -0.02169722,  0.36553407, -0.40219942],
        [ 0.43139988,  0.22985965, -0.03710729,  0.41512936,  0.27066517,
          0.17599058, -0.520954  ,  0.42753923,  0.17385381, -0.50503516],
        [ 0.4441123 ,  0.4497388 ,  0.11788124, -0.13655743,  0.13342291,
          0.53211033, -0.41852164,  0.19234025,  0.3317526 ,  0.3959934 ],
        [ 0.33512

# Testing serialization of tf objects

In [22]:
checkpoint = {
    "model_state_dict" : weight_manager.model_state_dict(model),
    "optimizer_state_dict" : optimizer.get_config()
}

In [23]:
with open(pathlib.Path.cwd() / "test_serialization", "wb") as f:
    cloudpickle.dump(checkpoint, f)

In [24]:
with open(pathlib.Path.cwd() / "test_serialization", "rb") as f:
        checkpoint = cloudpickle.load(f)

In [25]:
checkpoint

{'model_state_dict': OrderedDict([('config',
               {'name': 'sequential_1',
                'layers': [{'class_name': 'InputLayer',
                  'config': {'batch_input_shape': (None, 1),
                   'dtype': 'float32',
                   'sparse': False,
                   'ragged': False,
                   'name': 'dense_2_input'}},
                 {'class_name': 'Dense',
                  'config': {'name': 'dense_2',
                   'trainable': True,
                   'dtype': 'float32',
                   'batch_input_shape': (None, 1),
                   'units': 10,
                   'activation': 'linear',
                   'use_bias': True,
                   'kernel_initializer': {'class_name': 'GlorotUniform',
                    'config': {'seed': None}},
                   'bias_initializer': {'class_name': 'Zeros', 'config': {}},
                   'kernel_regularizer': None,
                   'bias_regularizer': None,
                   'ac